### signup
@url_dev = http://localhost:3056/v1/api/

POST {{url_dev}}shop/signup
Content-Type: application/json
x-api-key: 72eb8191375bc9ecabbffc3a40f5b2ab3be58ee585ea19ba36688436bc4c3c577da2c6061b8c5a85467d324cac789628aaf34422356125c1cc5ae335b4e3b607

{
    "name": "Shop Tips",
    "email": "ThiQuynhShop@example.com",
    "password": "abc123"
}
